### ISSUE TITLE
pypy3: implicit declaration of function ‘PyUnicode_DecodeUTF8Stateful’

### ISSUE THREAD

**Issue by mgorny** [peterjc/backports.lzma#30]
Now that we know how to solve PyPy problems, time to look at PyPy3 ;-). Not that it's very important given that it has a builtin lzma module but still we could fix it for completeness. The error is:

```
cc -pthread -fPIC -I/usr/lib64/pypy3/include -I/home/mgorny/include -I/opt/local/include -I/usr/local/include -I/usr/lib64/pypy3/include -c backports/lzma/_lzmamodule.c -o build/temp.linux-x86_64-3.5/backports/lzma/_lzmamodule.o
backports/lzma/_lzmamodule.c: In function ‘_PyUnicode_FromId’:
backports/lzma/_lzmamodule.c:87:18: warning: implicit declaration of function ‘PyUnicode_DecodeUTF8Stateful’ [-Wimplicit-function-declaration]
     id->object = PyUnicode_DecodeUTF8Stateful(id->string,
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
backports/lzma/_lzmamodule.c:87:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     id->object = PyUnicode_DecodeUTF8Stateful(id->string,
                ^
```

My initial guess is that the `PyUnicode_DecodeUTF8Stateful` is an internal CPython function that extensions are not supposed to use. [Documentation](https://docs.python.org/3/c-api/unicode.html#utf-8-codecs) does not include that function, and [random stackoverflow post](https://stackoverflow.com/a/36099157/165333) seems to confirm that.

**Comment by mgorny** [comment]
Ok, I must've been temporarily blinded. It's actually documented there. I'll file a PyPy3 bug then.

**Comment by mgorny** [comment]
Actually, PyPy3 has it [stubbed](https://bitbucket.org/pypy/pypy/src/912f3925af424e22fa3938eceaa6e921b08ea307/pypy/module/cpyext/stubs.py?at=default&fileviewer=file-view-default#stubs.py-1516), so it's currently not implemented.

**Comment by mgorny** [comment]
That said, FWICS the difference between 'regular' and 'stateful' function seems to be that the latter stops short on invalid UTF-8 while the former raises error. To be honest, this code looks weird and I'm not really sure it's intentional or merely some internal CPython 'optimization'.

**Comment by peterjc** [comment]
Still does not work on PyPy3.5 v6.0.0, see e.g. https://travis-ci.org/peterjc/backports.lzma/jobs/379647608

```
$ python test_lzma.py
Traceback (most recent call last):
  File "test_lzma.py", line 35, in <module>
    from backports import lzma
  File "/home/travis/pypy3.5-6.0.0-linux_x86_64-portable/site-packages/backports/lzma/__init__.py", line 25, in <module>
    from ._lzma import *
ImportError: /home/travis/pypy3.5-6.0.0-linux_x86_64-portable/site-packages/backports/lzma/_lzma.pypy3-60-x86_64-linux-gnu.so: undefined symbol: PyUnicode_DecodeUTF8Stateful
```

I have not checked to see if I can find any PyPy issues about this.

**Comment by peterjc** [comment]
On the bright side, PyPy3 already has lzma included, so getting the backport working here seems a very low priority.

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.
