### ISSUE TITLE
Compilation error in python 2.7.2

### ISSUE THREAD

**Issue by AbdealiJK** [peterjc/backports.lzma#17]
One of our users got the error - https://dpaste.de/uztv Which says:
```
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/root/include -I/opt/local/include -I/usr/local/include -I/usr/include/python2.7 -c backports/lzma/_lzmamodule.c -o build/temp.linux-x86_64-2.7/backports/lzma/_lzmamodule.o
  gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/backports/lzma/_lzmamodule.o -L/root/lib -L/opt/local/lib -L/usr/local/lib -L/usr/lib64 -llzma -lpython2.7 -o build/lib.linux-x86_64-2.7/backports/lzma/_lzma.so
  /bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
  /usr/local/lib/libpython2.7.a: error adding symbols: Bad value
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
```
This error was got when using python 2.7.2 . When they updated their python version, the compilation worked fine. It seems like the python 2.7.2 `libpython2.7.a` file does not have some symbols that later versions have.

**Comment by peterjc** [comment]
Can you confirm which version worked? Thanks!

**Comment by AbdealiJK** [comment]
@jayvdb could you answer that ?

**Comment by jayvdb** [comment]
I suspect it was just a local problem, with the wrong files in the wrong order in the linker path.

It compiles correctly on at least Python 2.7.3

https://travis-ci.org/jayvdb/backports.lzma/builds/135822280

If we're worried about 2.7.2, creating a 2.7.2 job on Travis using a pyenv will quickly confirm whether it is working or not.

**Comment by peterjc** [comment]
Thanks for the clarifications.

I'm going to close this issue since few people will be using Python 2.7.0 to 2.7.2, and it could have been specific to the one machine. We can reopen it if anything like this comes up again - Google will find the compilation error message here :)
